language: cpp
compiler: gcc

os: linux
dist: bionic
apt:
  sources:
    - sourceline: 'ppa:scottaiton/thunderegg-deps'
jobs:
  include:
  - addons:
      sonarcloud:
          organization: "thunderegg"
      apt:
        packages:
          - cmake
          - libfftw3-dev
          - libopenmpi-dev
          - openmpi-bin
          - petsc-dev
          - libblas-dev
          - liblapack-dev
          - libtrilinos-zoltan-dev
    after_script: 
        - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
        - sonar-scanner
  - addons:
      apt:
        packages:
          - cmake
          - libopenmpi-dev
          - openmpi-bin
          - petsc-dev
          - libblas-dev
          - liblapack-dev
          - libtrilinos-zoltan-dev
  - addons:
      apt:
        packages:
          - cmake
          - libfftw3-dev
          - libopenmpi-dev
          - openmpi-bin
          - libblas-dev
          - liblapack-dev
          - libtrilinos-zoltan-dev
before_install:
  - pip install --user cpp-coveralls
  - export CXXFLAGS="-std=c++11"
script:
  - export CXXFLAGS="-g -O0 -Wall -W -fprofile-arcs -ftest-coverage"
  - export CFLAGS="-g -O0 -Wall -W -fprofile-arcs -ftest-coverage"
  - export LDFLAGS="-lgcov"
  - cmake .
  - make
  - make test
after_success:
  - coveralls --include src --exclude src/Thunderegg/Experimental --gcov-options '\-lp'
