language: cpp
compiler: gcc

os: linux
dist: bionic
apt:
  sources:
    - sourceline: 'ppa:scottaiton/thunderegg-deps'
jobs:
  include:
  - addons:
      apt:
        packages:
          - cmake
          - libfftw3-dev
          - libopenmpi-dev
          - openmpi-bin
          - petsc-dev
          - libblas-dev
  - addons:
      apt:
        packages:
          - cmake
          - libopenmpi-dev
          - openmpi-bin
          - petsc-dev
          - libblas-dev
  - addons:
      apt:
        packages:
          - cmake
          - libfftw3-dev
          - libopenmpi-dev
          - openmpi-bin
          - libblas-dev
before_install:
  - pip install --user cpp-coveralls
  - export CXXFLAGS="-std=c++11"
script:
  - export CXXFLAGS="-g -O0 -Wall -W -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Woverloaded-virtual -Wwrite-strings -fprofile-arcs -ftest-coverage"
  - export CFLAGS="-g -O0 -Wall -W -fprofile-arcs -ftest-coverage"
  - export LDFLAGS="-lgcov"
  - cmake .
  - make
  - cd ../
  - make test
after_success:
  - coveralls --include src --exclude src/Thunderegg/Experimental --gcov-options '\-lp'
