ignore:
  - "test/**/*"
  - "test/*"
  - "apps/**/*"
  - "tpl/*"
  - "tpl/**/*"
  - "src/ThunderEgg/tpl/*"
  - "src/ThunderEgg/tpl/**/*"
  - "src/ThunderEgg/Experimental/**/*"
  - "src/ThunderEgg/Experimental/*"
