# - Try to find HYPRE
#

find_path (HYPRE_DIR NAMES include/HYPRE.h HINTS ENV HYPRE_DIR PATHS $ENV{HOME}/hypre DOC "Hypre Directory")

if(HYPRE_DIR)
  SET(HYPRE_INCLUDES ${HYPRE_DIR})
  find_path (HYPRE_INCLUDE_DIR NAMES HYPRE.h HINTS "${HYPRE_DIR}" PATH_SUFFIXES include NO_DEFAULT_PATH)
  list(APPEND HYPRE_INCLUDES ${HYPRE_INCLUDE_DIR})
  find_library(HYPRE_LIBRARIES NAMES HYPRE PATHS "${HYPRE_DIR}/lib" ${HYPRE_DIR})
ENDIF(HYPRE_DIR)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HYPRE REQUIRED_VARS HYPRE_LIBRARIES HYPRE_INCLUDE_DIR)
