name: Doxygen Generation
on:
  push:
    branches:
      - develop
      - develop-wip
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CXXFLAGS: -g -O0 -Wall -Wno-system-headers -Wno-unused-parameter -Wno-maybe-uninitialized -Wno-unknown-warning-option -fprofile-arcs -ftest-coverage -fno-inline -fno-inline-small-functions -fno-default-inline
      LDFLAGS: -lgcov
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake libfftw3-dev libopenmpi-dev openmpi-bin libpetsc-real3.12-dbg libblas-dev liblapack-dev ninja-build doxygen graphviz
    - uses: actions/checkout@v2
    - name: Cmake Configure
      run: cmake -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DPETSC_DIR=/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real-debug/ -GNinja .
    - name: Generate Doxygen
      run: ninja doc
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: ThunderEgg/thunderegg.github.io
        publish_branch: main
        publish_dir: ./doc/html
        destination_dir: docs/${{ steps.extract_branch.outputs.branch }}