name: Main ThunderEgg Build / Test / Analyze
on:
  push:
    paths-ignore:
      - '.github/workflows/doxygen.yml'
  pull_request:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
        - name: "gcc"
          preset: "ci-gcc"
          ubuntu_packages: "libfftw3-dev libopenmpi-dev openmpi-bin libpetsc-real3.12-dbg libblas-dev liblapack-dev"
          analyze: false
        - name: "clang"
          preset: "ci-clang"
          ubuntu_packages: "libfftw3-dev libopenmpi-dev openmpi-bin libpetsc-real3.12-dbg libblas-dev liblapack-dev llvm-11"
          analyze: true

    name: ${{ matrix.name }} Build on Linux
    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ${{ matrix.ubuntu_packages }} ccache

    - name: Prepare cache timestamp
      id: cache_timestamp
      run: |
        echo "timestamp=`date "+%Y-%m-%d-%H:%M:%S"`" >> $GITHUB_OUTPUT

    - name: ccache cache files
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ matrix.name }}-ccache-${{ steps.cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ matrix.name }}-ccache-

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: ${{ matrix.name }} workflow
      run: cmake --workflow --preset ${{ matrix.preset }}

    - name: log if fail
      if: failure()
      run: cat out/build/${{ matrix.preset }}/CMakeFiles/CMakeConfigureLog.yaml

    - name: Generate Coverage Report
      if: ${{ matrix.analyze }}
      run: |
        llvm-profdata-11 merge \
          -sparse out/test/${{ matrix.preset }}/test.profraw.* \
          -o test.profdata
        llvm-cov-11 show \
          --instr-profile=test.profdata \
          -object out/build/${{ matrix.preset }}/test/unit_tests_mpi1 \
          -object out/build/${{ matrix.preset }}/test/unit_tests_mpi2 \
          -object out/build/${{ matrix.preset }}/test/unit_tests_mpi3 \
          --ignore-filename-regex="((test|out|tpl)/.*)" \
          > coverage.txt

    - name: Upload to codecov.io
      if: ${{ matrix.analyze }}
      run: bash <(curl -s https://codecov.io/bash)
